/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2015-11-07 22:21:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class welcome_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("<form action=\"test.jsp\">\r\n");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.google.com/jsapi\"></script>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      google.load(\"visualization\", \"1\", {packages:[\"corechart\"]});\r\n");
      out.write("      //google.setOnLoadCallback(drawChart);\r\n");
      out.write("      function drawChart() {\r\n");
      out.write("        var data = google.visualization.arrayToDataTable([\r\n");
      out.write("          ['ID', 'Purpose', 'Presence',{ role: 'style' }],          \r\n");
      out.write("          ['',   79,  136,'color: #76A7FA'],\r\n");
      out.write("          ['',   78,  184,'color: #76A7FA'],\r\n");
      out.write("          ['',   72,  278,'color: #76A7FA'],\r\n");
      out.write("          ['',   81,  200,'color: #76A7FA'],\r\n");
      out.write("          ['',   72,  170,'color: #76A7FA'],\r\n");
      out.write("          ['',   68,  477,'color: #76A7FA'],\r\n");
      out.write("          ['Chetan',   80,  167,'color: #99FFCC']\r\n");
      out.write("        ]);\r\n");
      out.write("\r\n");
      out.write("        var options = {\r\n");
      out.write("          //colorAxis: {colors: ['yellow', 'red']},\r\n");
      out.write("\t\t  //colorAxis: {colors: []}\r\n");
      out.write("\t\t  vAxis: {title: 'Presence Score'},\t\t  \r\n");
      out.write("\t\t    hAxis: { \r\n");
      out.write("\t\t    \ttitle: 'Purpose Score',\r\n");
      out.write("\t\t        direction: -1, \r\n");
      out.write("\t\t        slantedText: true,\r\n");
      out.write("\t\t        slantedTextAngle: 90\r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t  bubble: {\r\n");
      out.write("\t\t\t  textStyle: {fontSize: 11},\r\n");
      out.write("\t\t\t  plotBackgroundImage:\"http://www.w3schools.com/html/pic_mountain.jpg\"}\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("        var chart = new google.visualization.BubbleChart(document.getElementById('chart_div'));\r\n");
      out.write("        chart.draw(data, options);\r\n");
      out.write("        //var boundingBox = chart.getChartLayoutInterface().getChartAreaBoundingBox(); \r\n");
      out.write("   \t//$('#chartBackground').css('background-position', boundingBox.left + \"px \" + boundingBox.top + \"px\").css('background-size', boundingBox.width + \"px \" + boundingBox.height + \"px\");\r\n");
      out.write("      }\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("<title>Way of Being! </title>\r\n");
      out.write("<style>\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("    <div id=\"chart_div\" style=\"width: 900px; height: 500px; background-image:url(\"pic_mountain.jpg\")></div>\r\n");
      out.write("    \r\n");
      out.write("<table>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td>I make basic mistakes because of carelessness, not paying attention, or thinking of something else.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("    <tr>\r\n");
      out.write("    <td>I value getting things done over finding deeper purpose (i.e. meaning) in what I am doing.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I find it difficult to stay focused on the present moment during meetings.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I get so busy that I forget to stop and appreciate life.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I find myself listening to a coworker with one ear, and doing something else at the same time.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I ask myself \"How many tasks can I accomplish before the day is through?\"</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I rush through activities without being paying close attention to them.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I get consumed by worries that I won't get everything done.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I fail to notice how I am feeling when speaking with a coworker.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I put job responsibilities above caring for myself and others.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I complete tasks automatically, without being aware of what I'm doing.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I forget that we only have one life to live.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I find myself preoccupied with the future or the past.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I judge my days by how much work I finish.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I find my mind wandering as if \"by itself\" when working.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I find myself preoccupied with making sure others complete their work rather than helping them <br> finds deeper meaning in their work.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I commute to and from work on \"auto-pilot\" without remembering what most of the trip was like.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  \r\n");
      out.write("      <tr>\r\n");
      out.write("    <td>I go through my day as if I will live forever.</td>\r\n");
      out.write("\t    <td><input type=\"radio\" name=\"choice1\" value=\"AmostAlways\">Almost Always \r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Somewhat Frequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Very Infrequently\r\n");
      out.write("\t    <input type=\"radio\" name=\"choice1\" value=\"VeryFrequently\">Almost Never\r\n");
      out.write("\t</td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("    \r\n");
      out.write("    <br><br><br>\r\n");
      out.write("  <input type=\"button\" value=\"Submit\" onclick=drawChart() />\r\n");
      out.write("</form>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
